=== JJediny/compliance-trestle/schema-documents/IBM_Cloud_security_and_compliance_scans_results_detailed_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "IBM Cloud Compliance & Security Scan Summary Results",
  "version": "0.1",
  "type": "object",
  "properties": {
    "profile": { "type": "string" },
    "control_number": { "type": "string" },
    "IT_resource": {"type": "string", "format": "ip-address" },
    "control_target": { "type": "string" },
    "actual_value": { "type": "string" },
    "expected_value": { "type": "string" },
    "status": { "type": "string",
                "enum": ["PASS", "FAIL"]
              },
    "detail": { "type": "string" }
  },
  "required": [
    "profile",
    "control_number",
    "IT_resource",
    "control_target",
    "status",
    "detail"
  ]
}

=== JJediny/compliance-trestle/schema-documents/sample_minimal_IBM_Cloud_security_and_compliance_scans_results_detailed.json
{
  "profile": "CIS CentOS Linux 7 Benchmark 2.2.0",
  "control_number": "6.1.11",
  "IT_resource": "192.168.1.5",
  "control_target": "centos",
  "actual_value": "[false]",
  "expected_value": "Unowned files or directories should not exist",
  "status": "PASS",
  "detail": "Unowned files or directories do not exist"
}
